# -*- coding: utf-8 -*-
"""mapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jeq3BJAlO9c4cDIN0Zt9izrBM6uR4Fwr
"""
import flair
import logging
from abc import abstractmethod
from pathlib import Path

from flair.datasets import (
    TWITTER_NER,
    WIKIGOLD_NER,
    WEBPAGES_NER,
    ColumnCorpus
)
from flair.data import Corpus

log = logging.getLogger("flair")
#
# class Mapping():
#     """
#     A simple mapping object to map down the datasets into the conll_3 tag
#     """
    #
    # def __init__(self, corpus, corpus_mapped):
    #     """
    #     Instantiate Mapping
    #     :param corpus: initial dataset
    #     :param corpus_mapped: dataset mapped into connl_4 tag set
    #     """
    #     self.corpus = corpus
    #     self.corpus_mapped = corpus_mapped


def twitter_ner_mapped():
    corpus_mapped = TWITTER_NER(
            label_name_map={'facility': 'O','movie': 'O','product': 'O','sportsteam': 'ORG','tvshow': 'O','other': 'O','person': 'PER','geo-loc': 'LOC','company': 'ORG', 'musicartist':'O'}
    )
    return corpus_mapped


def wikigold_ner_mapped():
    scorpus = WIKIGOLD_NER()
    return scorpus


def onto_ner_mapped():
    corpus_mapped: Corpus = ColumnCorpus(
            "resources/tasks/onto-ner",
            column_format={0: "text", 1: "pos", 2: "upos", 3: "ner"},
            tag_to_bioes="ner",
            label_name_map={'NORP': 'MISC', 'FAC': 'O', 'GPE': 'LOC', 'CARDINAL': 'O', 'DATE': 'O', 'EVENT': 'O',
                        'LANGUAGE': 'MISC', 'LAW': 'O', 'MONEY': 'O', 'ORDINAL': 'O', 'PERCENT': 'O',
                        'PRODUCT': 'MISC', 'QUANTITY': 'O', 'TIME': 'O', 'WORK_OF_ART': 'O', 'LOC': 'LOC',
                        'ORG': 'ORG', 'PERSON': 'PER'}
    )
    return corpus_mapped


def webpages_ner_mapped():
    scorpus = WEBPAGES_NER()
    return scorpus