# -*- coding: utf-8 -*-
"""mapping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jeq3BJAlO9c4cDIN0Zt9izrBM6uR4Fwr

Functions to map down the datasets into the conll3 format
"""

"""### Config"""

import flair
import logging
from abc import abstractmethod
from pathlib import Path

from flair.datasets import (
    TWITTER_NER,
    WIKIGOLD_NER,
    WEBPAGES_NER,
    ColumnCorpus
)
from flair.data import Corpus

log = logging.getLogger("flair")


"""#### Twitter Mapping"""

def twitter_ner_mapped():
    corpus_mapped = TWITTER_NER(
            label_name_map={'facility': 'O','movie': 'O','product': 'O','sportsteam': 'ORG','tvshow': 'O','other': 'O','person': 'PER','geo-loc': 'LOC','company': 'ORG', 'musicartist':'O'}
    )
    return corpus_mapped


"""#### Wikipedia Mapping"""

def wikigold_ner_mapped():
    scorpus = WIKIGOLD_NER()
    return scorpus


"""#### Ontoner Mapping"""

def onto_ner_mapped():
    corpus_mapped: Corpus = ColumnCorpus(
            "resources/tasks/onto-ner",
            column_format={0: "text", 1: "pos", 2: "upos", 3: "ner"},
            label_name_map={'NORP': 'MISC', 'FAC': 'LOC', 'GPE': 'LOC', 'CARDINAL': 'O', 'DATE': 'O', 'EVENT': 'MISC',
                        'LANGUAGE': 'MISC', 'LAW': 'MISC', 'MONEY': 'O', 'ORDINAL': 'O', 'PERCENT': 'O',
                        'PRODUCT': 'MISC', 'QUANTITY': 'O', 'TIME': 'O', 'WORK_OF_ART': 'MISC', 'LOC': 'LOC', 'PERSON': 'PER'}
    )
    return corpus_mapped


"""#### Webpages Mapping"""

def webpages_ner_mapped():
    scorpus = WEBPAGES_NER()
    return scorpus